### ISSUE TITLE
Conflicting names for IPA keytab file

### ISSUE THREAD

**Issue by abrad3** [SSSD/sssd-ci-containers#96]
In this repo, the IPA test keytab file is `/enrollment/ipa.test.keytab`. However, in the tests it seems to expect it to be called `/enrollment/ipa.keytab`. I couldn't run tests on IPA until I renamed `/enrollment/ipa.test.keytab` to `/enrollment/ipa.keytab`.
I tested the fix by running the solution to task 16 at https://tests.sssd.io/en/latest/course/course.html#take-the-course

Which name is the one that should be used? Once I know, I can make a PR to fix this.

**Comment by abrad3** [comment]
I've noticed the same issue happens with samba- which makes sense, it uses the same naming convention

**Comment by jakub-vavra-cz** [comment]
Hi,
this was changed as preparation for setups that might have multiple ipa, ad servers/domains.
The course needs fixing to reflect the updated mhc.yaml. 

See: https://github.com/SSSD/sssd/blob/master/src/tests/system/mhc.yaml

Regards,
Jakub

cc: @pbrezina

**Comment by abrad3** [comment]
I'm no longer seeing this issue- not sure if it was fixed by something on your end or mine- I hadn't pulled from master in a while so it might have been me. So I'm going to close this!
